### ISSUE TITLE
MoS2.json

### ISSUE THREAD

**Issue by Amitavalanl** [aztan2/charged-defects-framework#1]
Hi 

What does the "d_slab" mean in the MoS2.json in your Jupyter notebook? And from where we get the "d_slab" value?

**Comment by aztan2** [comment]
d_slab is the thickness of the monolayer used to construct the dielectric model. We estimate d_slab together with the averaged slab dielectric constant eps_slab according to the expressions given in section 3 of the tutorial_2D_pristine.ipynb .
